version: '3'
services:
  #Mysql service
  mysql_souscription:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=souscription
    ports:
      - "3309:3306"
  #Back-end Spring Boot Application
  microservice-souscription:
    image: bibndiaye/microservice-souscription
    ports:
      - "8500:8500"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_souscription:3306/souscription?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      #build:
      #context: "./"
      #dockerfile: "Dockerfile"
    depends_on:
      - mysql_souscription
#Front-end Angular Application
#  frontend:
#      build: ../cimrpoc-web/
#      links:
#             - "microservice-souscription"
#      depends_on:
#             - "microservice-souscription"
#      ports:
#             - "8082:80"
